// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
)

const exampleQuery = `-- name: ExampleQuery :many
SELECT id FROM users
`

func (q *Queries) ExampleQuery(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, exampleQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
